### ISSUE TITLE
Remove console.logs

### ISSUE THREAD

**Issue by ipinto** [tarkil/Enhanced-Production-Warning-Bar#13]
When you have the extension enabled, next console.logs are printed in the console:

Download the React DevTools for a better development experience: https://fb.me/react-devtools
environment list[object Object]

IMHO, a Chrome extension should not print anything than errors in the log.

**Comment by tarkil** [comment]
I forgot to remove one console log, sorry. On the other hand, I have added a new target to remove the react devtools message, see README.
